/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    weddings: Wedding;
    users: User;
    'rsvp-responses': RsvpResponse;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    weddings: WeddingsSelect<false> | WeddingsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'rsvp-responses': RsvpResponsesSelect<false> | RsvpResponsesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "weddings".
 */
export interface Wedding {
  id: number;
  /**
   * e.g., "Emma & John"
   */
  coupleName: string;
  /**
   * For SaaS: emma-john (leave empty for single wedding)
   */
  subdomain?: string | null;
  /**
   * Optional custom domain for this wedding
   */
  customDomain?: string | null;
  weddingDate: string;
  /**
   * Deactivate to disable this wedding site
   */
  isActive?: boolean | null;
  venueName: string;
  venueAddress: string;
  /**
   * For map display
   */
  venueCoordinates: {
    latitude: number;
    longitude: number;
  };
  /**
   * Timeline of events during the wedding day
   */
  schedule?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * The wedding this user belongs to (optional for super admin)
   */
  wedding?: (number | null) | Wedding;
  /**
   * Admin: Super admin or wedding admin | Guest: Invited guest with PIN login
   */
  role: 'admin' | 'guest';
  /**
   * Used as username for guest login
   */
  fullName: string;
  /**
   * Auto-generated PIN for guest login. Share this with the guest.
   */
  pin?: string | null;
  /**
   * Number of additional guests this person can bring (0 = just them)
   */
  allowedPlusOnes?: number | null;
  /**
   * Is this person the main contact who will fill RSVP?
   */
  isPrimaryContact?: boolean | null;
  /**
   * When the invitation was sent to this guest
   */
  invitationSentDate?: string | null;
  /**
   * Generated QR code data URL or identifier
   */
  qrCode?: string | null;
  /**
   * Private notes about this guest (not visible to guest)
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
  /**
   * Required for admins. Guests provide email when they RSVP.
   */
  email?: string | null;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rsvp-responses".
 */
export interface RsvpResponse {
  id: number;
  /**
   * The wedding this RSVP is for
   */
  wedding: number | Wedding;
  /**
   * The guest who submitted this RSVP
   */
  guest: number | User;
  /**
   * Name of the person who submitted (for easy reference)
   */
  guestName: string;
  /**
   * Is the guest attending the wedding?
   */
  isAttending: boolean;
  /**
   * Total number of people attending (including +1s)
   */
  guestCount: number;
  /**
   * Contact email for future communication
   */
  email: string;
  /**
   * Overall dietary restrictions for the group
   */
  dietaryRestrictions?: string | null;
  /**
   * Details for each person attending
   */
  attendees?:
    | {
        name: string;
        /**
         * Specific restrictions for this person
         */
        dietaryRestrictions?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Any additional comments or questions from the guest
   */
  additionalNotes?: string | null;
  submittedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'weddings';
        value: number | Wedding;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'rsvp-responses';
        value: number | RsvpResponse;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "weddings_select".
 */
export interface WeddingsSelect<T extends boolean = true> {
  coupleName?: T;
  subdomain?: T;
  customDomain?: T;
  weddingDate?: T;
  isActive?: T;
  venueName?: T;
  venueAddress?: T;
  venueCoordinates?:
    | T
    | {
        latitude?: T;
        longitude?: T;
      };
  schedule?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  wedding?: T;
  role?: T;
  fullName?: T;
  pin?: T;
  allowedPlusOnes?: T;
  isPrimaryContact?: T;
  invitationSentDate?: T;
  qrCode?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rsvp-responses_select".
 */
export interface RsvpResponsesSelect<T extends boolean = true> {
  wedding?: T;
  guest?: T;
  guestName?: T;
  isAttending?: T;
  guestCount?: T;
  email?: T;
  dietaryRestrictions?: T;
  attendees?:
    | T
    | {
        name?: T;
        dietaryRestrictions?: T;
        id?: T;
      };
  additionalNotes?: T;
  submittedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}