/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    tenants: Tenant;
    users: User;
    'wedding-info': WeddingInfo;
    media: Media;
    gallery: Gallery;
    guests: Guest;
    'rsvp-responses': RsvpResponse;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'wedding-info': WeddingInfoSelect<false> | WeddingInfoSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    gallery: GallerySelect<false> | GallerySelect<true>;
    guests: GuestsSelect<false> | GuestsSelect<true>;
    'rsvp-responses': RsvpResponsesSelect<false> | RsvpResponsesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: number;
  /**
   * e.g., "Emma & John"
   */
  coupleName: string;
  /**
   * For SaaS: emma-john (leave empty for single wedding)
   */
  subdomain?: string | null;
  /**
   * Optional custom domain for this wedding
   */
  customDomain?: string | null;
  weddingDate: string;
  /**
   * Deactivate to disable this wedding site
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * The wedding this user belongs to (optional for first admin)
   */
  tenant?: (number | null) | Tenant;
  /**
   * Admin: Full access | Guest: Can only RSVP
   */
  role: 'admin' | 'guest';
  /**
   * Used as username for guest login
   */
  fullName: string;
  /**
   * For guest authentication (will be hashed)
   */
  pin?: string | null;
  /**
   * Group name for family members sharing login
   */
  familyGroup?: string | null;
  /**
   * Total number of people allowed (including primary guest)
   */
  allowedGuestCount?: number | null;
  updatedAt: string;
  createdAt: string;
  /**
   * Optional for guests, required for admins
   */
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wedding-info".
 */
export interface WeddingInfo {
  id: number;
  /**
   * The wedding this information belongs to
   */
  tenant: number | Tenant;
  title: string;
  ceremonyDateTime: string;
  venueName: string;
  venueAddress: string;
  /**
   * For map display
   */
  venueCoordinates: {
    latitude: number;
    longitude: number;
  };
  /**
   * e.g., "Our Story" or "How We Met"
   */
  storyTitle?: string | null;
  /**
   * Your love story or how you met
   */
  storyContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Any extra details for guests
   */
  additionalInfo?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * e.g., "Formal", "Cocktail", "Beach Casual"
   */
  dresscode?: string | null;
  /**
   * Timeline of events during the wedding day
   */
  schedule?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * The wedding this media belongs to
   */
  tenant: number | Tenant;
  /**
   * Description of the image for accessibility
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery".
 */
export interface Gallery {
  id: number;
  /**
   * The wedding this gallery belongs to
   */
  tenant: number | Tenant;
  /**
   * e.g., "Engagement Photos", "Pre-Wedding"
   */
  title: string;
  /**
   * Optional description of this gallery
   */
  description?: string | null;
  images?:
    | {
        image: number | Media;
        /**
         * Optional caption for this image
         */
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Uncheck to hide this gallery from guests
   */
  isPublished?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guests".
 */
export interface Guest {
  id: number;
  /**
   * The wedding this guest is invited to
   */
  tenant: number | Tenant;
  /**
   * Link to the user account for this guest
   */
  user: number | User;
  fullName: string;
  /**
   * Group name for family members (e.g., "Smith Family")
   */
  familyGroup: string;
  /**
   * Is this person the main contact who will fill RSVP?
   */
  isPrimaryContact?: boolean | null;
  /**
   * Number of additional guests this person can bring (0 = just them)
   */
  allowedPlusOnes?: number | null;
  /**
   * When the invitation was sent to this guest
   */
  invitationSentDate?: string | null;
  /**
   * Generated QR code data URL or identifier
   */
  qrCode?: string | null;
  /**
   * Private notes about this guest (not visible to guest)
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rsvp-responses".
 */
export interface RsvpResponse {
  id: number;
  /**
   * The wedding this RSVP is for
   */
  tenant: number | Tenant;
  /**
   * The guest who submitted this RSVP
   */
  guest: number | Guest;
  /**
   * Name of the person who submitted (for easy reference)
   */
  guestName: string;
  /**
   * Is the guest attending the wedding?
   */
  isAttending: boolean;
  /**
   * Total number of people attending (including +1s)
   */
  guestCount: number;
  /**
   * Contact email for future communication
   */
  email: string;
  /**
   * Overall dietary restrictions for the group
   */
  dietaryRestrictions?: string | null;
  /**
   * Details for each person attending
   */
  attendees?:
    | {
        name: string;
        /**
         * Specific restrictions for this person
         */
        dietaryRestrictions?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Any additional comments or questions from the guest
   */
  additionalNotes?: string | null;
  submittedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'tenants';
        value: number | Tenant;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'wedding-info';
        value: number | WeddingInfo;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'gallery';
        value: number | Gallery;
      } | null)
    | ({
        relationTo: 'guests';
        value: number | Guest;
      } | null)
    | ({
        relationTo: 'rsvp-responses';
        value: number | RsvpResponse;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  coupleName?: T;
  subdomain?: T;
  customDomain?: T;
  weddingDate?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  tenant?: T;
  role?: T;
  fullName?: T;
  pin?: T;
  familyGroup?: T;
  allowedGuestCount?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wedding-info_select".
 */
export interface WeddingInfoSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  ceremonyDateTime?: T;
  venueName?: T;
  venueAddress?: T;
  venueCoordinates?:
    | T
    | {
        latitude?: T;
        longitude?: T;
      };
  storyTitle?: T;
  storyContent?: T;
  additionalInfo?: T;
  dresscode?: T;
  schedule?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  tenant?: T;
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery_select".
 */
export interface GallerySelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  description?: T;
  images?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  isPublished?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guests_select".
 */
export interface GuestsSelect<T extends boolean = true> {
  tenant?: T;
  user?: T;
  fullName?: T;
  familyGroup?: T;
  isPrimaryContact?: T;
  allowedPlusOnes?: T;
  invitationSentDate?: T;
  qrCode?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rsvp-responses_select".
 */
export interface RsvpResponsesSelect<T extends boolean = true> {
  tenant?: T;
  guest?: T;
  guestName?: T;
  isAttending?: T;
  guestCount?: T;
  email?: T;
  dietaryRestrictions?: T;
  attendees?:
    | T
    | {
        name?: T;
        dietaryRestrictions?: T;
        id?: T;
      };
  additionalNotes?: T;
  submittedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}